services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    volumes:
      - user_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - cloud_network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: password
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    volumes:
      - files_storage:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - cloud_network
    restart: unless-stopped

  redis:
    container_name: redis_cache
    image: redis:alpine
    environment:
      REDIS_PASSWORD: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - cloud_network
    restart: unless-stopped

volumes:
  user_data:
  files_storage:
  redis_data:

networks:
  cloud_network:
    driver: bridge