spring:
  mvc:
    static-path-pattern: /**

  data:
    redis:
      host: ${REDIS_HOST:redis_cache}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis}

  session:
    timeout: 3600
    redis:
      namespace: cloud:sessions
      flush-mode: immediate

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/user_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

minio:
  endpoint: http://localhost:9000
  access-key: ${MINIO_ACCESS_KEY:minio}
  secret-key: ${MINIO_SECRET_KEY:password}
  bucket: user-files

server:
  port: 8080
  address: 0.0.0.0

logging:
  level:
    org.springframework.security: DEBUG  # Логи Spring Security
    org.springframework.web: DEBUG       # Логи HTTP-запросов
    com.qubb.cloud: DEBUG                # Логи вашего приложения (опционально)
